### ISSUE TITLE
New functions.

### ISSUE THREAD

**Issue by hazehigh** [afffsdd/AntiLP#3]
Yo,c0der nice tool for feed but after update antilp showes "game finished" if i minimalize game. Earlier i can minimalize game and watch movie, serials etc.... without any problems. Pls make your tool working in minimalize mode will be really nice.
Also please add auto-ranked matchmaking feed mode for easy derank on smurf accounts and auto-picker for all pick mode. thx for advance imba coder 1337 lmao

**Comment by hazehigh** [comment]
also add pls auto-buyer (boots for faster feed) auto-restart the tool if antilp cant detect the team. thx

**Comment by afffsdd** [comment]
ok

**Comment by hazehigh** [comment]
thx brother best coder eu wew

**Comment by afffsdd** [comment]
im actually in the process of rewriting it
